import type { ProjectRecord } from "@/types/project";

export const bookEasyProject: ProjectRecord = {
  slug: "bookeasy",
  name: "BookEasy",
  shortSummary: null,
  description: null,
  problem: null,
  goals: [],
  role: null,
  features: [],
  architecture: null,
  technologyStack: [],
  challenges: [],
  solutions: [],
  currentStatus: null,
  implementationStatus: "draft",
  demoStatus: "pending",
  repositoryVisibility: "private",
  repositoryUrl: null,
  liveDemoUrl: null,
  desktopScreenshots: [],
  mobileScreenshots: [],
  accessibilityNotes: [],
  performanceNotes: [],
  lessonsLearned: [],
  statusNotes: ["Pending owner input"],
  isFeatured: false,
};
