import type { ProjectRecord } from "@/types/project";

export const taskOrbitProject: ProjectRecord = {
  slug: "taskorbit",
  name: "TaskOrbit",
  homepageSummary:
    "A SaaS productivity platform with authentication, protected workflows, structured task management, and scalable application foundations.",
  shortSummary:
    "A full-stack SaaS management platform focused on structured workflows, authentication, protected application experiences, and scalable task and productivity foundations.",
  description: null,
  problem: null,
  goals: [],
  role: null,
  features: [],
  architecture: null,
  technologyStack: [
    "Next.js",
    "React",
    "TypeScript",
    "Tailwind CSS",
    "Node.js",
    "Database-backed application architecture",
  ],
  homepageTechnologyStack: ["Next.js", "TypeScript", "React", "Tailwind CSS", "Node.js"],
  challenges: [],
  solutions: [],
  currentStatus: "Active Development",
  implementationStatus: "backend-integrated",
  demoStatus: "available",
  repositoryVisibility: "private",
  repositoryUrl: null,
  liveDemoUrl: "https://taskorbit-mu.vercel.app/",
  desktopScreenshots: [
    {
      src: "/images/projects/taskorbit/01-primary-desktop.png",
      alt: "TaskOrbit dashboard with workspace overview and active workspace switching.",
      width: 1440,
      height: 900,
    },
    {
      src: "/images/projects/taskorbit/02-workflow-desktop.png",
      alt: "TaskOrbit project overview with lifecycle controls, project settings, and project membership.",
      width: 1440,
      height: 900,
    },
    {
      src: "/images/projects/taskorbit/03-tasks-desktop.png",
      alt: "TaskOrbit project task directory with task filters, counts, and task cards.",
      width: 1440,
      height: 900,
    },
    {
      src: "/images/projects/taskorbit/04-task-detail-desktop.png",
      alt: "TaskOrbit task detail view with task state, dependencies, and update controls.",
      width: 1440,
      height: 900,
    },
    {
      src: "/images/projects/taskorbit/05-team-desktop.png",
      alt: "TaskOrbit workspace team page with members, invitations, and access management.",
      width: 1440,
      height: 900,
    },
  ],
  mobileScreenshots: [],
  accessibilityNotes: [],
  performanceNotes: [],
  lessonsLearned: [],
  statusNotes: [
    "Private repository",
    "Authentication foundations and core SaaS application experiences are implemented",
    "Do not invent collaboration statistics, organizations, users, revenue, or production adoption",
  ],
  isFeatured: true,
};
